import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en" className={cn("font-sans")}>
        <body className="antialiased">{children}</body>
      </html>
    </ConvexClerkProvider>
  );
}
